services:
  # 1. 采集器 (Collector) - OpenTelemetry 统一入口
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      # Expose OTLP gRPC for all data types (Metrics, Logs, Traces)
      - "4317:4317"
      # Expose OTLP HTTP for all data types (Metrics, Logs, Traces)
      - "4318:4318"
    depends_on:
      - openobserve

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    volumes:
      - ./data:/data
    ports:
      - 5080:5080
      - 5081:5081
    environment:
      ZO_ROOT_USER_EMAIL: root@example.com
      ZO_ROOT_USER_PASSWORD: "Complexpass#123"
